# Spring settings
spring:
  profiles:
    active: dev
  redis:
    password: ${REDIS_PASSWORD}
    #host: localhost
    #port: 6379
    database: 0
    cluster:
      max-redirects: ${REDIS_CLUSTER_MAX_REDIRECTS}
      nodes: ${REDIS_CLUSTER_NODES}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
