# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:8080}

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      incarcloud: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: redis-achieve
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redis2019}
    database: ${REDIS_DATABASE:0}
    cluster:
      max-redirects: ${REDIS_CLUSTER_MAX_REDIRECTS:6}
      nodes: ${REDIS_CLUSTER_NODES:10.0.11.22:7001,10.0.11.23:7001,10.0.11.24:7001,10.0.11.22:7011,10.0.11.23:7011,10.0.11.24:7011}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
